sudo: false

language: node_js
node_js: "8"

cache: yarn

install: yarn

script:
  - yarn run compile
  - yarn test

deploy:
  provider: script
  script: ./build/travis/zip-files.sh
  on:
    condition: $(./build/travis/should-deploy.sh)
